server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8000
  servlet:
    context-path: /note

spring:
  # ActiveMQ 设置服务器地址 账号以及密码
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  # ActiveMQ 设置队列还是主题
  jms:
    pub-sub-domain: false     # false: Queue队列（默认）  true: Topic主题  影响监听器的启用，启用队列的监听器还是主题的监听器？







# ActiveMQ 自己定义队列名称、自定义主题名称
myActiveQueue: boot-activemq-queue
myActiveTopic: boot-activemq-topic